### ISSUE TITLE
[Epic] - Make it easier to start developing with miranum connect

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/miranum#115]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
We should simplify it to start with the development of Miranum Connect.
Getting Started examples are needed for this -> like this: https://docs.camunda.org/get-started/quick-start/
Moreover we should think about creating a initializer similar to https://github.com/spring-io/initializr
-> Please refer: https://docs.spring.io/initializr/docs/current/reference/html/#create-instance

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] <your-issue-here>
```

## Stakeholder
@dominikhorn93 

# Acceptance
- Getting Started Landing Page in Docs with chapter per case
- Each Getting Started has its own git repository
- The Getting Started can be used as a seed project
- Following Getting Started are created
  - Simple C7/C8 Worker created
  - Hexagonal Architecture Style
  - Process Start
  - Message Correlation

**Comment by DaAnda97** [comment]
Hi @Hafflgav,
I've forked your repo and added it as one of our consulting projects: https://github.com/FlowSquad/miranum-consulting/tree/feat/pizza-e-vino

**Comment by Hafflgav** [comment]
> Hi @Hafflgav,
> I've forked your repo and added it as one of our consulting projects: https://github.com/FlowSquad/miranum-consulting/tree/feat/pizza-e-vino

Hey @DaAnda97! 
Isn't this part of this story: https://github.com/orgs/FlowSquad/projects/9/views/1?filterQuery=label%3Aconsulting&pane=issue&itemId=23820378
