### ISSUE TITLE
Starting Spring context with miranum dependencies fails

### ISSUE THREAD

**Issue by xdoo** [Miragon/miranum#198]
**Describe the bug**
I have created a new Spring Boot project (via https://start.spring.io/). Ran the application test - context boots up and everything works. After that I have added

connect
process-api

as dependencies into pom.xml, ran the test again and got the following error: 

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'miranumProcessApi' defined in class path resource [io/miragon/miranum/connect/process/ProcessAutoConfiguration.class]: Unsatisfied dependency expressed through method 'miranumProcessApi' parameter 0: No qualifying bean of type 'io.miragon.miranum.connect.process.impl.StartProcessPort' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**To Reproduce**
1. Create basic Sprint Boot project (with spring web)
2. Add "connect" and "process-api"
3. Run application test

**Expected behavior**
Adding a dependency should not crash the entire project.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Open JDK 18

**Comment by xdoo** [comment]
What I miss in the documentation is a simple (and working) example of how to launch a process instance from within Spring. I don't really need a hexagonal architecture for that. If I want to use that in my application, then I do - but that has nothing to do with the functionality of miranum-connect. But what is essential, for example, is a camunda.bpm.client.url (this is in the Camunda documentation, but for me it definitely belongs to a Quick Start example). More focus on miranum connect would be helpful for me.

There is nothing against making an (advanced) example for a hexagonal architecture, but it should be consistent in itself (see DTO, see waiter process calling a waiter).

**Comment by Hafflgav** [comment]
Hey @xdoo! 
Thank you for sharing your feedback. I will take a closer look on that later today. 

If you are looking for an example without hexagonal architecture check out: https://github.com/Miragon/miranum-connect-basic-template
