### ISSUE TITLE
Miranum Worker mapping can not map json-string to object

### ISSUE THREAD

**Issue by DaAnda97** [Miragon/miranum#360]
On a simple example I'm implementing a c7 bpmn process with two service tasks. The first one writes an object to the engine, the second one reads it. While reading I get the following exception:

``` java
java.lang.IllegalArgumentException: Cannot construct instance of `io.test.ExampleObject` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value () at [Source: UNKNOWN; byte offset: #UNKNOWN]
```

My ExampleObject looks like this:
``` java

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ExampleObject {

    private List<ExampleInner> inner;
}

---
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ExampleInner {

    private String value;
}
```

I was able to break the issue down to Jackson Object mapper, which uses mapper.convertValue(jsonString, ExampleObject.class). Replacing it with mapper.readValue(jsonString, ExampleObject.class) worked without issues. Please fix that!

**Comment by dominikhorn93** [comment]
sounds like a valid solution to me.
